/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RegisterTeacherRouteImport } from './routes/register.teacher'
import { Route as RegisterStudentRouteImport } from './routes/register.student'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AppTeasersRouteImport } from './routes/app.teasers'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppFlashcardsRouteImport } from './routes/app.flashcards'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppDocumentsIdRouteImport } from './routes/app.documents.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterTeacherRoute = RegisterTeacherRouteImport.update({
  id: '/register/teacher',
  path: '/register/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterStudentRoute = RegisterStudentRouteImport.update({
  id: '/register/student',
  path: '/register/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeasersRoute = AppTeasersRouteImport.update({
  id: '/app/teasers',
  path: '/app/teasers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/app/notes',
  path: '/app/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/app/library',
  path: '/app/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFlashcardsRoute = AppFlashcardsRouteImport.update({
  id: '/app/flashcards',
  path: '/app/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/app/analytics',
  path: '/app/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDocumentsIdRoute = AppDocumentsIdRouteImport.update({
  id: '/app/documents/$id',
  path: '/app/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/changelog': typeof ChangelogRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/gdpr': typeof GdprRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notes': typeof AppNotesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/teasers': typeof AppTeasersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/register/student': typeof RegisterStudentRoute
  '/register/teacher': typeof RegisterTeacherRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/app/documents/$id': typeof AppDocumentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/changelog': typeof ChangelogRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/gdpr': typeof GdprRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notes': typeof AppNotesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/teasers': typeof AppTeasersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/register/student': typeof RegisterStudentRoute
  '/register/teacher': typeof RegisterTeacherRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/app/documents/$id': typeof AppDocumentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/changelog': typeof ChangelogRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/gdpr': typeof GdprRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notes': typeof AppNotesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/teasers': typeof AppTeasersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/register/student': typeof RegisterStudentRoute
  '/register/teacher': typeof RegisterTeacherRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/app/documents/$id': typeof AppDocumentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/changelog'
    | '/community'
    | '/contact'
    | '/features'
    | '/gdpr'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/app/analytics'
    | '/app/flashcards'
    | '/app/library'
    | '/app/notes'
    | '/app/settings'
    | '/app/teasers'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/register/student'
    | '/register/teacher'
    | '/admin/'
    | '/app/'
    | '/teacher/'
    | '/app/documents/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/changelog'
    | '/community'
    | '/contact'
    | '/features'
    | '/gdpr'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/app/analytics'
    | '/app/flashcards'
    | '/app/library'
    | '/app/notes'
    | '/app/settings'
    | '/app/teasers'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/register/student'
    | '/register/teacher'
    | '/admin'
    | '/app'
    | '/teacher'
    | '/app/documents/$id'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/changelog'
    | '/community'
    | '/contact'
    | '/features'
    | '/gdpr'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/app/analytics'
    | '/app/flashcards'
    | '/app/library'
    | '/app/notes'
    | '/app/settings'
    | '/app/teasers'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/register/student'
    | '/register/teacher'
    | '/admin/'
    | '/app/'
    | '/teacher/'
    | '/app/documents/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ChangelogRoute: typeof ChangelogRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  GdprRoute: typeof GdprRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppFlashcardsRoute: typeof AppFlashcardsRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppNotesRoute: typeof AppNotesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeasersRoute: typeof AppTeasersRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  RegisterStudentRoute: typeof RegisterStudentRoute
  RegisterTeacherRoute: typeof RegisterTeacherRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppIndexRoute: typeof AppIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  AppDocumentsIdRoute: typeof AppDocumentsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/teacher': {
      id: '/register/teacher'
      path: '/register/teacher'
      fullPath: '/register/teacher'
      preLoaderRoute: typeof RegisterTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/student': {
      id: '/register/student'
      path: '/register/student'
      fullPath: '/register/student'
      preLoaderRoute: typeof RegisterStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/teasers': {
      id: '/app/teasers'
      path: '/app/teasers'
      fullPath: '/app/teasers'
      preLoaderRoute: typeof AppTeasersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/app/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/library': {
      id: '/app/library'
      path: '/app/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/flashcards': {
      id: '/app/flashcards'
      path: '/app/flashcards'
      fullPath: '/app/flashcards'
      preLoaderRoute: typeof AppFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/app/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/documents/$id': {
      id: '/app/documents/$id'
      path: '/app/documents/$id'
      fullPath: '/app/documents/$id'
      preLoaderRoute: typeof AppDocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ChangelogRoute: ChangelogRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  GdprRoute: GdprRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppFlashcardsRoute: AppFlashcardsRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppNotesRoute: AppNotesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeasersRoute: AppTeasersRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  RegisterStudentRoute: RegisterStudentRoute,
  RegisterTeacherRoute: RegisterTeacherRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppIndexRoute: AppIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  AppDocumentsIdRoute: AppDocumentsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
